/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 *
 * RFSim replay of recorded SRS/CSI-RS channels.
 *
 * The .bin files used by this engine (generated by gui/npy_to_rfsim_bin.py)
 * contain sparse time-domain impulse taps per rx/tx path.  Replay performs a
 * direct linear convolution over the continuous RFSim sample stream, matching
 * the behavior of the normal time-domain channel model (rxAddInput()).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "openair1/SIMULATION/TOOLS/sim.h"
#include "common/platform_types.h"
#include "rfsimulator.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define REPLAY_MAGIC       0x48534D52
#define REPLAY_VERSION     3
#define MAX_REPLAY_SLOTS   100
#define MAX_TAPS_PER_PATH  64

typedef struct {
  uint32_t magic;
  uint16_t version;
  uint8_t  num_rx_ant;
  uint8_t  num_tx_ant;
  uint16_t fft_size;
  uint16_t n_rb;
  uint32_t subcarrier_spacing;
  uint32_t num_slots_recorded;
  uint16_t max_active_taps;
  uint16_t reserved_offset;
  uint8_t  n_symbols;
  uint8_t  reserved[23];
} __attribute__((packed)) replay_file_header_t;

typedef struct {
  uint16_t delay;
  c16_t    tap;
} replay_tap_t;

typedef struct {
  uint16_t       count;
  replay_tap_t  *taps;
} replay_path_t;

// ---- Replay state ----
static struct {
  int    loaded;
  int    tried_load;
  int    num_rx;
  int    num_tx;
  int    fft_size;
  int    num_slots;
  int    current_slot;
  int    tap_scale_bits;   /* stored taps are scaled by 2^tap_scale_bits */
  replay_path_t *paths;    /* [num_slots][rx*ntx+tx] */
} replay = {0};

int srs_replay_loaded = 0;

static void free_paths(void) {
  if (replay.paths) {
    const int paths_per_slot = replay.num_rx * replay.num_tx;
    for (int s = 0; s < replay.num_slots; s++)
      for (int p = 0; p < paths_per_slot; p++)
        free(replay.paths[s * paths_per_slot + p].taps);
    free(replay.paths);
    replay.paths = NULL;
  }
  replay.num_slots = 0;
}

int rfsim_load_srs_file(const char *path) {
  FILE *fp = fopen(path, "rb");
  if (!fp) return -1;

  replay_file_header_t hdr;
  if (fread(&hdr, sizeof(hdr), 1, fp) != 1) { fclose(fp); return -1; }
  if (hdr.magic != REPLAY_MAGIC || hdr.version != REPLAY_VERSION) {
    fclose(fp);
    return -1;
  }
  if (hdr.num_rx_ant == 0 || hdr.num_tx_ant == 0 ||
      hdr.max_active_taps == 0 || hdr.max_active_taps > MAX_TAPS_PER_PATH) {
    fclose(fp);
    return -1;
  }

  free_paths();

  replay.num_rx = hdr.num_rx_ant;
  replay.num_tx = hdr.num_tx_ant;
  replay.fft_size = hdr.fft_size;
  replay.tap_scale_bits = hdr.reserved[0];
  if (replay.tap_scale_bits < 1 || replay.tap_scale_bits > 15)
    replay.tap_scale_bits = 15;

  const int total_slots = hdr.num_slots_recorded;
  replay.num_slots = total_slots > MAX_REPLAY_SLOTS ? MAX_REPLAY_SLOTS : total_slots;
  replay.current_slot = 0;
  if (replay.num_slots <= 0) {
    fclose(fp);
    return -1;
  }

  const int paths_per_slot = replay.num_rx * replay.num_tx;
  const int skip_slots = total_slots - replay.num_slots;
  replay.paths = calloc((size_t)replay.num_slots * paths_per_slot,
                        sizeof(replay_path_t));
  if (!replay.paths) { fclose(fp); return -1; }

  for (int s = 0; s < total_slots; s++) {
    uint32_t slot_number;
    if (fread(&slot_number, sizeof(slot_number), 1, fp) != 1) {
      free_paths();
      fclose(fp);
      return -1;
    }

    const int store_idx = s - skip_slots;
    for (int p = 0; p < paths_per_slot; p++) {
      uint16_t count = 0;
      if (fread(&count, sizeof(count), 1, fp) != 1 ||
          count > hdr.max_active_taps) {
        free_paths();
        fclose(fp);
        return -1;
      }
      if (store_idx < 0) {
        // Discard old slots while advancing through the file.
        fseek(fp, count * (sizeof(uint16_t) + sizeof(c16_t)), SEEK_CUR);
        continue;
      }

      replay_path_t *dst = &replay.paths[(size_t)store_idx * paths_per_slot + p];
      dst->count = count;
      if (count == 0)
        continue;
      dst->taps = calloc(count, sizeof(replay_tap_t));
      if (!dst->taps) {
        free_paths();
        fclose(fp);
        return -1;
      }
      for (int k = 0; k < count; k++) {
        if (fread(&dst->taps[k].delay, sizeof(uint16_t), 1, fp) != 1 ||
            fread(&dst->taps[k].tap, sizeof(c16_t), 1, fp) != 1) {
          free_paths();
          fclose(fp);
          return -1;
        }
      }
    }
  }
  fclose(fp);

  replay.loaded = 1;
  srs_replay_loaded = 1;

  LOG_I(HW,
        "[rfsim] Loaded SRS channel file: %s (%d slots, %dx%d, fft=%d, "
        "taps/path<=%d, tap_scale_bits=%d)\n",
        path, replay.num_slots, replay.num_rx, replay.num_tx, replay.fft_size,
        hdr.max_active_taps, replay.tap_scale_bits);
  return 0;
}

// ---- Direct time-domain linear convolution ----
static void apply_replay_taps(c16_t **input_sig,
                              cf_t *after_channel_sig,
                              int rxAnt,
                              channel_desc_t *channelDesc,
                              int nbSamples) {
  if (rxAnt >= replay.num_rx || replay.num_slots <= 0) {
    memset(after_channel_sig, 0, nbSamples * sizeof(cf_t));
    return;
  }

  const int slot_idx = replay.current_slot % replay.num_slots;
  const int paths_per_slot = replay.num_rx * replay.num_tx;
  const int path_base = slot_idx * paths_per_slot + rxAnt * replay.num_tx;
  const double tap_scale = (double)(1 << replay.tap_scale_bits);

  memset(after_channel_sig, 0, nbSamples * sizeof(cf_t));

  for (int n = 0; n < nbSamples; n++) {
    double acc_r = 0.0;
    double acc_i = 0.0;

    for (int tx = 0; tx < replay.num_tx; tx++) {
      const replay_path_t *path = &replay.paths[path_base + tx];
      for (int k = 0; k < path->count; k++) {
        const int d = path->taps[k].delay;
        if (n < d)
          continue;
        const c16_t x = input_sig[tx][n - d];
        const c16_t h = path->taps[k].tap;
        acc_r += ((double)x.r * h.r - (double)x.i * h.i) / tap_scale;
        acc_i += ((double)x.r * h.i + (double)x.i * h.r) / tap_scale;
      }
    }

    after_channel_sig[n].r += acc_r;
    after_channel_sig[n].i += acc_i;
  }

  const double pathLossLinear = pow(10, channelDesc->path_loss_dB / 20.0);
  const double noise_per_sample =
      pow(10, channelDesc->noise_power_dB / 10.0) * 256;
  for (int n = 0; n < nbSamples; n++) {
    after_channel_sig[n].r *= pathLossLinear;
    after_channel_sig[n].i *= pathLossLinear;
    after_channel_sig[n].r += noise_per_sample * gaussZiggurat(0.0, 1.0);
    after_channel_sig[n].i += noise_per_sample * gaussZiggurat(0.0, 1.0);
  }

  // One read call covers all RX antennas; advance once on the last one.
  if (rxAnt == replay.num_rx - 1)
    replay.current_slot++;
}

// Called per RX antenna with the same signature as the original channel model.
void rxAddInput_srsfile(c16_t **input_sig,
                        cf_t *after_channel_sig,
                        int rxAnt,
                        channel_desc_t *channelDesc,
                        int nbSamples) {
  if (!replay.loaded && !replay.tried_load) {
    replay.tried_load = 1;
    const char *replay_path = getenv("CHANNEL_FILE");
    if (replay_path) {
      LOG_I(HW, "[rfsim] Loading channel file: %s\n", replay_path);
      if (rfsim_load_srs_file(replay_path) != 0)
        LOG_W(HW, "Failed to load channel file: %s\n", replay_path);
    } else {
      LOG_I(HW, "[rfsim] CHANNEL_FILE not set, using normal channel model\n");
    }
  }

  if (!replay.loaded) {
    rxAddInput(input_sig, after_channel_sig, rxAnt, channelDesc, nbSamples);
    return;
  }

  apply_replay_taps(input_sig, after_channel_sig, rxAnt, channelDesc, nbSamples);
}
